### ISSUE TITLE
TODO: Features

### ISSUE THREAD

**Issue by dvub** [dvub/comprs#1]
### Features
- [ ] Sidechain input (and parameterization)
- [ ] Multiple Level Detection Types (RMS, Peak, etc.)
### Ops
- [ ] Configure GH Actions to compile a release and make it available
